### ISSUE TITLE
Arima 4 enzyme 

### ISSUE THREAD

**Issue by AlcaArctica** [hugp-ri/hicup-plus#2]
Does the hicup-plus pipeline work with the Arima 4 enzyme high coverage kit? As far as I can see, it is currently written with an assumption that 2 enzymes are used?

**Comment by Kelly-ST-HRI** [comment]
That's correct. As mentioned in the [documentation](https://hicup-plus.readthedocs.io/en/latest/), `--arima` is an alias for `--re1 ^GATC,DpnII:G^ANTC,Arima`. Note that `hicup_digester` can support multiple enzymes as custom input. I've not tested if more than 2 are possible but if you know the target sequence of the restriction site for each it can be configured.

> --re1
> Restriction enzyme used to digest the genome (the enzyme that forms the ligation junction) e.g. A^GATCT,BglII. Some Hi-C > protocols may use two enzymes at this stage. To specify two enzymes: -1 A^GATCT,BglII:A^AGCTT,HindIII.

I'll note that similar issues with Arima configuration have been discussed here which may be helpful to you. https://github.com/nf-core/hic/issues/64

I checked the specifications [here](https://arimagenomics.com/wp-content/files/User-Guide-Arima-High-Coverage-for-Animal-Tissue.pdf) but they do not list the names of the enzymes or their target sites. Perhaps you may be able to get this information if you contact Arima Genomics technical support as a customer?

Let me know if there is anything I can do to help but this is not a priority of our development team. I could add another alias for the new high coverage kit or test 3 or more enzymes if I know the target site sequences.

**Comment by Kelly-ST-HRI** [comment]
I'll share information based on the [Arima Genomics FAQs](https://arimagenomics.com/faqs/).

> What is the difference between the 2 enzyme and 4 enzyme options of the Arima HiC chemistry?
>
> Our 2-enzyme chemistry is our most widely utilized option for samples that focus on the spatial organization of genomes, the scaffolding of ne novo assemblies and the identification of large-scale structural variants. The 4-enzyme chemistry improves access to a larger portion of genomes with more extreme GC content and adds utility beyond the spatial genome analysis like phased de novo assembly and comprehensive phased variant calling.

> What are the restriction enzymes in Arima Hi-C?
>
> The Arima-HiC chemistry uses restriction enzymes that digest chromatin at ^GATC and G^ANTC, where N can be any of the 4 genomic bases. Our multiple restriction enzyme chemistry produces the following possible ligation junction motifs: GATCGATC, GANTGATC, GANTANTC, GATCANTC.

> Are there any program or file modifications that I will need to begin my data analysis?
>
> For several open-source Hi-C data analysis tools, you will need to have knowledge of the restriction enzyme cut site motifs and/or genomic locations, as well as the possible ligation junction motifs produced by the Arima-HiC chemistry. This information is commonly used for read trimming and downstream Hi-C data processing. The Arima-HiC chemistry uses restriction enzymes that digest chromatin at ^GATC and G^ANTC, where N can be any of the 4 genomic bases. Our multiple restriction enzyme chemistry produces the following possible ligation junction motifs: GATCGATC, GANTGATC, GANTANTC, GATCANTC. Please contact [technical support](mailto:techsupport@arimagenomics.com) for more information about how to appropriately implement open-source Hi-C data analysis tools with respect to Arima-HiC chemistry. We will also be happy to share a link to download cut site location files for mouse and human genome builds or help you generate custom cut site location files for your genome of interest.

They also have the following resources:
[Bioinformatics User Guide](https://resources.arimagenomics.com/arima-bioinformatics-user-guide)
[High Coverage Kit User Guide](https://arimagenomics.com/wp-content/files/User-Guide-Arima-High-Coverage-for-Animal-Tissue.pdf)
[Arima Genomics GitHub org](https://github.com/ArimaGenomics/)

**Comment by Kelly-ST-HRI** [comment]
I've tested the following HICUP digester calls with HiCUP v0.8.3:

> $ hicup_digester --genome hg38re2 --re1 "A^GATCT,BglII:A^AGCTT,HindIII" hg38.fa
> HiCUP Digester (version 0.8.3)
> Digesting files
> Digesting 'hg38.fa'
> Digestion complete

Output: Digest_hg38re2_BglII_HindIII_None_13-20-43_14-12-2023.txt

> $ hicup_digester --genome hg38re3 --re1 "A^GATCT,BglII:A^AGCTT,HindIII:C^CATGG,NcoI" hg38.fa
> HiCUP Digester (version 0.8.3)
> Digesting files
> Digesting 'hg38.fa'
> Digestion complete

Output: Digest_hg38re3_BglII_HindIII_NcoI_None_13-22-39_14-12-2023.txt

> $ hicup_digester --genome hg38re4 --re1 "A^GATCT,BglII:A^AGCTT,HindIII:C^CATGG,NcoI:C^CGG,MspI" hg38.fa
> HiCUP Digester (version 0.8.3)
> Digesting files
> Digesting 'hg38.fa'
> Digestion complete

Output: Digest_hg38re4_BglII_HindIII_NcoI_MspI_None_13-24-27_14-12-2023.txt

Therefore the current digester script can handle 3 or 4 enzymes as custom inputs using the string input parameter format demonstrated here. There have only been minor modifications to this subroutine in HiCUP 0.9.2 or HiCUP+ to my knowledge so it should also be supported for these.

Note that `--arima` input specifically uses 2 enzymes and is an alias for convenience to call this same job.
https://github.com/hugp-ri/hicup-plus/blob/de6cff9409ea85f4a82315b41e6345522d0850ae/hicup_digester#L285-L287

I'll close this issue as I've confirmed that custom inputs will work for 4 enzyme kits. Please consult with Arima genomics if you do not know the target sites for the additional enzymes. If you share the cut site parameters for the high coverage kit, a similar alias could be added on request.
